<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecurityReview.Domain\SecurityReview.Domain.csproj" />
    <ProjectReference Include="..\SecurityReview.ParserContracts\SecurityReview.ParserContracts.csproj" />
    <ProjectReference Include="..\SecurityReview.RulePack\SecurityReview.RulePack.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
