<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecurityReview.Domain\SecurityReview.Domain.csproj" />
    <ProjectReference Include="..\SecurityReview.Application\SecurityReview.Application.csproj" />
    <ProjectReference Include="..\SecurityReview.Infrastructure\SecurityReview.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\rules\trusted-signers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\SecurityReviewTool.ico" />
    <Resource Include="Assets\SecurityReviewTool.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>SecurityReviewTool</AssemblyName>
    <ApplicationIcon>Assets\SecurityReviewTool.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>
