<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SecurityReview.Domain\SecurityReview.Domain.csproj" />
    <ProjectReference Include="..\..\src\SecurityReview.Application\SecurityReview.Application.csproj" />
    <ProjectReference Include="..\..\src\SecurityReview.ParserContracts\SecurityReview.ParserContracts.csproj" />
    <ProjectReference Include="..\..\src\SecurityReview.Parsers\SecurityReview.Parsers.csproj" />
    <ProjectReference Include="..\..\src\SecurityReview.RulePack\SecurityReview.RulePack.csproj" />
    <ProjectReference Include="..\..\src\SecurityReview.Infrastructure\SecurityReview.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
